### ISSUE TITLE
Space padding in f strings

### ISSUE THREAD

**Issue by ecoppen** [yxnagi/Brampton-Manor-Coding#5]
https://github.com/yxnagi/Programming-Challenges/blob/547003f01a2f381952deda7f73cae4e9b6115185/Github/Brampton%20Manor%20Academy/Programming%20Challenge%202/main.py#L14

https://github.com/yxnagi/Programming-Challenges/blob/547003f01a2f381952deda7f73cae4e9b6115185/Github/Brampton%20Manor%20Academy/Programming%20Challenge%202/main.py#L20

https://saralgyaan.com/posts/f-string-in-python-usage-guide/#How_to_add_space_padding_in_Python_f-strings?

**Comment by AhrarArib** [comment]
Sir I have updated the new code with the padding included but it only seems to work for the strings but not the variables?

**Comment by ecoppen** [comment]
If you have a look at your longest string you'll see that it's 22 characters wide. In your code, you're only giving space for 20 which means that it overflows into the next set of data.

https://github.com/yxnagi/Brampton-Manor-Coding/blob/7acc7c0045a13eec1ad1a853d6c3b7a1a4ac82c4/Github/Brampton%20Manor%20Academy/Programming%20Challenge%202/main.py#L14-L20

The fix? Look at the maximum space required and then give a few extra spaces - the first doesn't need 20 for example.

```
def showlist(richtervalues):
    print(f"{'richter':<10}{'joules':<30}{'TNT':<30}")
    for x in richtervalues:
        richter = x
        joules = findenergy(richter)
        tnt = findtnt(joules)

        print(f"{richter:<10}{joules:<30}{tnt:<30}")
```
